name: season_display 
description:  This is useful flutter package for analyzing seasons and you can easily use  it by my hardwork
version: 1.0.5
homepage: https://github.com/Bakhodir95/season_display.git
repository: https://github.com/Bakhodir95/season_display.git


environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  
  test: ^1.25.2


